config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] 
  resources :users, :only => [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :cameras do  
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :maps
  root 'hello#index'
  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camera.rb
class Camera < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :user

    def user
        return User.find_by(id: self.user_id)
    end

    has_many :comments, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :camera

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :camera
  

  validates_uniqueness_of :camera_id, scope: :user_id

end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
  end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        has_many :camera, dependent: :destroy
        has_many :messages, dependent: :destroy
        has_many :entries, dependent: :destroy

        
        validates :name, presence: true
        validates :profile, length: { maximum: 200 }

        mount_uploader :image, ImageUploader

        def posts
          return Camera.where(user_id: self.id)
        end

        has_many :comments, dependent: :destroy

        has_many :likes, dependent: :destroy
        has_many :liked_cameras, through: :likes, source: :camera

        def already_liked?(camera)
          self.likes.exists?(camera_id: camera.id)
        end

        has_many :relationships
        has_many :followings, through: :relationships, source: :follow
        has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
        has_many :followers, through: :reverse_of_relationships, source: :user

        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end

        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end

        def following?(other_user)
          self.followings.include?(other_user)
        end
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @cameras = Camera.all

        

        if params[:search] == nil
            @cameras= Camera.all
        elsif params[:search] == ''
            @cameras= Camera.all
        else
            @cameras = Camera.where("title LIKE ? ",'%' + params[:search] + '%')
        end
    end



    def new
        @camera = Camera.new
    end

    def show
        @camera = Camera.find(params[:id])
        @user = User.find_by(id: @camera.user_id)

        @comments = @camera.comments
        @comment = Comment.new
    end

    def create
        camera = Camera.new(camera_params)

        camera.user_id = current_user.id

            if camera.save
                redirect_to :action => "index"
            else
                redirect_to :action => "new"
            end
    end

   
    def edit
        @camera = Camera.find(params[:id])
    end

    def destroy
        camera = Camera.find(params[:id])
    camera.destroy
    redirect_to action: :index
    end

    def update
            camera = Camera.find(params[:id])
        if camera.update(camera_params)
        redirect_to :action => "show", :id => camera.id
        else
        redirect_to :action => "new"
        end
    end

    private

    def camera_params
        params.require(:camera).permit(:image, :user_id, :title)
    end
    
end

  

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    
    def index
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
        @maps = Map.all
        @map = Map.new
    end

    def create
        map = Map.new(map_params)
        if map.save
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    def destroy
        map = Map.find(params[:id])
        map.destroy
        redirect_to action: :index
    end

    private
    def map_params
    params.require(:map).permit(:address, :latitude, :longitude)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cameras/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <div>
            <h3>編集</h3>
                <div>
                    <%= form_for @camera do |f| %>
                            <%= f.file_field :image %>
                            <br>
                            <%= f.label :title %>
                            <%= f.text_field :title, :size => 140 %> 
                        
                        <%= f.submit "編集する" %>
                    <% end %>
                </div>

            <%= link_to "一覧に戻る", cameras_path %>
            
        </div>

    </body>
</html>

app/views/cameras/index.html.erb
<%= link_to "TOPへ", root_path %>
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_camera_path %>
<h3>投稿を検索</h3>

<%= form_tag({controller:"cameras",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
<% end %>

<div class="cameras-container">
    <% @cameras.each do |t| %>
        <div class="camera4">
            <%= image_tag t.image_url, size: "250x200" if t.image? %>
                <br><%= t.title %>

                <br><a href="/users/<%= t.user.id %>"><%= t.user.name %></a>

                    
                <br><%= link_to "詳細へ", camera_path(t.id) %></br>

                <% if user_signed_in? && current_user.id == t.user_id %> 
                        <%= link_to "編集する", edit_camera_path(t.id) %>
                        <%= button_to "削除する", camera_path(t.id), method: :delete %>                                            
                <% end %>
        </div>
    <% end %>
    <div>
</div>

<% if user_signed_in? %>

   
<% end %>


app/views/cameras/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
<h3>新規投稿</h3>
    <%= form_for @camera do |f| %>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>

    <br><%= f.label :title %>
    <%= f.text_field :title, :size => 140 %>
  </div>
  
  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "一覧に戻る", cameras_path %>
    </body>
</html>

app/views/cameras/show.html.erb
<h3>投稿詳細</h3>
<div class="camera4">
<%= image_tag @camera.image.url, id: :image_prev, size: "250x200" if @camera.image? %>
    <p><%= @camera.title %></p>
    <%= @user.name %>
</div>

<div class="comment-wrapper">

<% if user_signed_in? %>

    <%= form_with(model: [@camera, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
            <% end %>
        
<% end %>
<% end %>

    <p>コメント一覧</p>
    <% @comments.each do |c| %>
        <div>
            <%= c.user.email unless c.user.blank? %>
            <br>
            <%= c.content %>
        </div>
            <br>
            <% if user_signed_in? && current_user.id == c.user_id %>  
        <%= button_to "削除する", camera_comment_path(c.camera.id, c.id), method: :delete %>
      <% end %>
    <% end %>
</div>


<% if user_signed_in? %>
    <% if current_user.already_liked?(@camera) %>
        <%= link_to camera_like_path(@camera), method: :delete do %>
            <p>いいねを取り消す</p><%= @camera.likes.count %>
        <% end %>
    <% else %>
        <%= link_to camera_likes_path(@camera), method: :post do %>
            <p>いいね</p><%= @camera.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <p>いいねの数 = </p><%= @camera.likes.count %>
<% end %>

<%= link_to "一覧に戻る", cameras_path %>
</div>